// publish-cli.test.js — black-box tests for wecom/commands/publish.sh
// against a capture HTTP server standing in for the adapter (via
// WECOM_ADAPTER_URL). Pins the jg-d0xr finding-2 contract: ONE
// idempotency key per logical invocation, generated by the CLI, reused
// verbatim across transport retries, echoed to the operator on failure
// so a manual rerun can resume instead of duplicating the send.

import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

const scriptPath = fileURLToPath(new URL('../../commands/publish.sh', import.meta.url));

const pngBytes = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  Buffer.from('IHDR fake image payload'),
]);

// The script shells out to jq/curl/uuidgen; skip (visibly) where the
// host lacks them rather than failing the suite on an unrelated box.
function hasTool(name) {
  const dirs = (process.env.PATH ?? '').split(path.delimiter);
  return dirs.some((d) => d && fs.existsSync(path.join(d, name)));
}
const toolsPresent = hasTool('jq') && hasTool('curl');

function tmpDir(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wecom-cli-test-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  return dir;
}

// startCaptureServer records every request body; respond(record, n) maps
// the 1-based request ordinal to { status, body }.
function startCaptureServer(t, respond) {
  const requests = [];
  const server = http.createServer((req, res) => {
    let body = '';
    req.setEncoding('utf8');
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      const record = { url: req.url, body: JSON.parse(body) };
      requests.push(record);
      const { status = 200, payload = { delivered: true, message_id: 'MSG_1' } } = respond(record, requests.length) ?? {};
      res.writeHead(status, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(payload));
    });
  });
  t.after(() => server.close());
  return new Promise((resolve) => {
    server.listen(0, '127.0.0.1', () => {
      resolve({ requests, url: `http://127.0.0.1:${server.address().port}/publish` });
    });
  });
}

function runPublish(args, adapterURL) {
  return new Promise((resolve) => {
    execFile('sh', [scriptPath, ...args], {
      env: {
        ...process.env,
        WECOM_ADAPTER_URL: adapterURL,
        GC_CITY_NAME: 'testcity',
        GC_SESSION_ID: '',
      },
    }, (err, stdout, stderr) => {
      resolve({ code: err?.code ?? 0, stdout, stderr });
    });
  });
}

test('a media publish carries one CLI-generated idempotency key', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const dir = tmpDir(t);
  const file = path.join(dir, 'photo.png');
  fs.writeFileSync(file, pngBytes);
  const { requests, url } = await startCaptureServer(t, () => ({}));

  const run = await runPublish(['--chat', 'zhang_san', '--image', file], url);
  assert.equal(run.code, 0, run.stderr);
  assert.equal(requests.length, 1);
  assert.ok(requests[0].url.endsWith('/publish-media'));
  assert.match(requests[0].body.idempotency_key, /^wecom-cli-[0-9a-f-]+$/);
});

test('an explicit --idempotency-key is sent verbatim, so a rerun resumes the same send', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const dir = tmpDir(t);
  const file = path.join(dir, 'photo.png');
  fs.writeFileSync(file, pngBytes);
  const { requests, url } = await startCaptureServer(t, () => ({}));

  await runPublish(['--chat', 'zhang_san', '--image', file, '--idempotency-key', 'key-op-retry'], url);
  await runPublish(['--chat', 'zhang_san', '--image', file, '--idempotency-key=key-op-retry'], url);
  assert.equal(requests.length, 2);
  assert.equal(requests[0].body.idempotency_key, 'key-op-retry');
  assert.equal(requests[1].body.idempotency_key, 'key-op-retry');
});

test('a transport retry reuses the SAME key instead of minting a new one', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const dir = tmpDir(t);
  const file = path.join(dir, 'photo.png');
  fs.writeFileSync(file, pngBytes);
  // First attempt 500s (curl --retry re-POSTs it), second succeeds.
  const { requests, url } = await startCaptureServer(t, (record, n) => (
    n === 1 ? { status: 500, payload: { delivered: false } } : {}
  ));

  const run = await runPublish(['--chat', 'zhang_san', '--image', file], url);
  assert.equal(run.code, 0, run.stderr);
  assert.equal(requests.length, 2, 'curl should have retried the transient 500 once');
  assert.equal(requests[0].body.idempotency_key, requests[1].body.idempotency_key,
    'a fresh key on the transport retry re-sends media the chat already saw');
});

test('a failed media publish tells the operator which key resumes it', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const dir = tmpDir(t);
  const file = path.join(dir, 'photo.png');
  fs.writeFileSync(file, pngBytes);
  // 501 is not on curl's transient-retry list, so exactly one attempt.
  const { requests, url } = await startCaptureServer(t, () => (
    { status: 501, payload: { delivered: false, failure_kind: 'provider_error' } }
  ));

  const run = await runPublish(['--chat', 'zhang_san', '--image', file], url);
  assert.equal(run.code, 1);
  assert.equal(requests.length, 1);
  const key = requests[0].body.idempotency_key;
  assert.match(run.stderr, new RegExp(`retry with --idempotency-key ${key}`));
});

// Codex jg-d0xr round-2 finding 2: with `set -e`, an exhausted curl
// transport failure exited from the command substitution BEFORE the
// generated key was ever printed — if the first request delivered but all
// responses were lost, the operator's natural rerun minted a fresh key
// and duplicated the media. The key must reach the operator before any
// network I/O, and a transport failure must name it again.
test('a transport failure with every response lost still surfaces the resume key', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const dir = tmpDir(t);
  const file = path.join(dir, 'photo.png');
  fs.writeFileSync(file, pngBytes);
  // Bind-and-close an ephemeral port so nothing listens: curl exhausts
  // its connection retries and exits non-zero without any HTTP response.
  const deadPort = await new Promise((resolve) => {
    const s = http.createServer();
    s.listen(0, '127.0.0.1', () => {
      const { port } = s.address();
      s.close(() => resolve(port));
    });
  });

  const run = await runPublish(['--chat', 'zhang_san', '--image', file], `http://127.0.0.1:${deadPort}/publish`);
  assert.equal(run.code, 1, `the script must fail deliberately, not die under set -e (stderr: ${run.stderr})`);
  const keyMention = run.stderr.match(/--idempotency-key (wecom-cli-[0-9a-f-]+)/);
  assert.ok(keyMention, `stderr must name the resume key on a transport failure; got: ${run.stderr}`);
  assert.match(run.stderr, /resume this send without duplicating/);
  // The key is printed BEFORE the request goes out, so even a killed curl
  // leaves the operator holding it: the first stderr line names it.
  assert.match(run.stderr.split('\n')[0], /idempotency key wecom-cli-/);
});

test('text publishes pass --idempotency-key through and omit it otherwise', { skip: !toolsPresent && 'jq/curl not on PATH' }, async (t) => {
  const { requests, url } = await startCaptureServer(t, () => ({}));

  await runPublish(['--chat', 'zhang_san', '--text', 'hello'], url);
  await runPublish(['--chat', 'zhang_san', '--text', 'hello', '--idempotency-key', 'key-text'], url);
  assert.equal(requests.length, 2);
  assert.ok(!('idempotency_key' in requests[0].body), 'bare text publishes stay byte-identical to the old wire');
  assert.equal(requests[1].body.idempotency_key, 'key-text');
});
